language: node_js

node_js:
  - iojs-v2

before_install:
  - make -C apiary install

script:
  - make -C apiary test

cache:
  directories:
    - apiary/node_modules
    - node_modules

deploy:
  provider: script
  script: make -C apiary publish
  skip_cleanup: true
  on:
    branch: master
